path_classifiers:
  test:
    - test
  library:
    - lib3

queries:
  - exclude: py/import-and-import-from

extraction:
  python:
    python_setup:
      version: 3
    index:
      exclude:
        - lib3

